apiVersion: v1
kind: Service
metadata:
  name: content-web
  labels:
    app: content-web
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: content-web
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webapp-route
  annotations: 
  - external-dns.alpha.kubernetes.io/target: endpoint.mycluster.hack.dev
spec:
  gateways:
    - istio-system/ingress-gateway
  hosts:
  - team1.mycluster.hack.dev
  http:
  - name: "default-route"
    match:
    - uri:
        prefix: "/*"
    route:
    - destination:
        host: content-api.team1
