apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webapp-route
  annotations: 
    external-dns.alpha.kubernetes.io/target: gateway.<cluster FQDN goes here>
spec:
  gateways:
    - istio-system/ingress-gateway
  hosts:
  - <team name>.<cluster FQDN goes here>
  http:
  - name: "default-route"
    match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: <service-name>.<namespace>
